item {
  id: 0
  name: 'dur'
}

item {
  id: 1
  name: 'durak'
}

item {
  id: 2
  name: 'solaDonulmez'
}

item {
  id: 3
  name: 'sagaDonulmez'
}

item {
  id: 4
  name: 'girilmez'
}

item {
  id: 6
  name: 'parkYasak'
}

item {
  id: 7
  name: 'park'
}

item {
  id: 11
  name: 'test'
}

item {
  id: 13
  name: 'ileriVeyaSolaGit'
}

item {
  id: 14
  name: 'ileriVeyaSagaGit'
}

item {
  id: 15
  name: 'hizSiniri30'
}
